
package org.osanchezhuerta.employees.hr.ws.web.facade;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeesHRService", targetNamespace = "http://facade.web.ws.hr.employees.osanchezhuerta.org/", wsdlLocation = "file:/home/osanchezhuerta/code/java/personal/employees-hr-ws-app/employees-hr-ws-app/employees-hr-ws-web/src/main/resources/wsdl/EmployeesHRService.wsdl")
public class EmployeesHRService
    extends Service
{

    private final static URL EMPLOYEESHRSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEESHRSERVICE_EXCEPTION;
    private final static QName EMPLOYEESHRSERVICE_QNAME = new QName("http://facade.web.ws.hr.employees.osanchezhuerta.org/", "EmployeesHRService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/osanchezhuerta/code/java/personal/employees-hr-ws-app/employees-hr-ws-app/employees-hr-ws-web/src/main/resources/wsdl/EmployeesHRService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEESHRSERVICE_WSDL_LOCATION = url;
        EMPLOYEESHRSERVICE_EXCEPTION = e;
    }

    public EmployeesHRService() {
        super(__getWsdlLocation(), EMPLOYEESHRSERVICE_QNAME);
    }

    public EmployeesHRService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEESHRSERVICE_QNAME, features);
    }

    public EmployeesHRService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEESHRSERVICE_QNAME);
    }

    public EmployeesHRService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEESHRSERVICE_QNAME, features);
    }

    public EmployeesHRService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeesHRService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeesHRServicePortType
     */
    @WebEndpoint(name = "EmployeesHRServiceHttpSoap11Endpoint")
    public EmployeesHRServicePortType getEmployeesHRServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://facade.web.ws.hr.employees.osanchezhuerta.org/", "EmployeesHRServiceHttpSoap11Endpoint"), EmployeesHRServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeesHRServicePortType
     */
    @WebEndpoint(name = "EmployeesHRServiceHttpSoap11Endpoint")
    public EmployeesHRServicePortType getEmployeesHRServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://facade.web.ws.hr.employees.osanchezhuerta.org/", "EmployeesHRServiceHttpSoap11Endpoint"), EmployeesHRServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEESHRSERVICE_EXCEPTION!= null) {
            throw EMPLOYEESHRSERVICE_EXCEPTION;
        }
        return EMPLOYEESHRSERVICE_WSDL_LOCATION;
    }

}
